name: chnroute

env:
  GITHUB_TOKEN: ${{ secrets.ACC_TOKEN }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  chnroute_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make sync
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto update $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
